// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOqGV-xYG4IVT6AKa8Rg5tDKtFCdc6k4Y',
    appId: '1:466089872991:web:f2a7e50c9835a5556dd5ea',
    messagingSenderId: '466089872991',
    projectId: 'auth-985c1',
    authDomain: 'auth-985c1.firebaseapp.com',
    storageBucket: 'auth-985c1.appspot.com',
    measurementId: 'G-QWGEV4V62J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPekewhe8GE-d9wntWJF_XTYrkh8snASY',
    appId: '1:466089872991:android:212f5a7575a3d8ec6dd5ea',
    messagingSenderId: '466089872991',
    projectId: 'auth-985c1',
    storageBucket: 'auth-985c1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZGiaYHpYODuTC2wKny6SByOb0JdAnCuI',
    appId: '1:466089872991:ios:6dabf0e7ec9679686dd5ea',
    messagingSenderId: '466089872991',
    projectId: 'auth-985c1',
    storageBucket: 'auth-985c1.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZGiaYHpYODuTC2wKny6SByOb0JdAnCuI',
    appId: '1:466089872991:ios:6dabf0e7ec9679686dd5ea',
    messagingSenderId: '466089872991',
    projectId: 'auth-985c1',
    storageBucket: 'auth-985c1.appspot.com',
    iosBundleId: 'com.example.authApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOqGV-xYG4IVT6AKa8Rg5tDKtFCdc6k4Y',
    appId: '1:466089872991:web:e55911e0f2e7e2616dd5ea',
    messagingSenderId: '466089872991',
    projectId: 'auth-985c1',
    authDomain: 'auth-985c1.firebaseapp.com',
    storageBucket: 'auth-985c1.appspot.com',
    measurementId: 'G-X9X12FSKZ3',
  );
}
